fix exec_extern_func
OCamlPro/owi pull request #57
Opened 2023-09-19 16:29 UTC by zapashcanon

cc @chambart

2023-09-19 16:34 UTC, chambart requested changes

2023-09-19 16:34 UTC, chambart commented on src/interpret.ml
> +        | _ -> assert false )
This can be reached. This should be a proper error

2023-09-26 10:55 UTC, zapashcanon commented
@chambart PTAL, while doing this, I had to change the type of `pop_arg` (because it can fail now).

This led me to realize we could simplify a lot of the code in the interpreter: I removed all the `Result` wrapping in `Env.get_*` functions.

2023-09-26 16:09 UTC, chambart commented
This looks like a nice improvement.

2023-09-26 16:18 UTC, merged